use super::{MemoryCategory, MemoryItem, MemoryStatus};

/// Exports memories for a connection to structured Markdown (LUCENT.md).
pub fn export_to_markdown(connection_key: &str, memories: &[MemoryItem]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Lucent Database Rules: {connection_key}\n\n"));
    out.push_str("> Auto-generated by Lucent Memory Subsystem. Edit or commit to version control.\n\n");

    let categories = [
        (MemoryCategory::Metric, "Metrics"),
        (MemoryCategory::Join, "Joins"),
        (MemoryCategory::Quirk, "Quirks"),
        (MemoryCategory::Preference, "Preferences"),
    ];

    for (cat, title) in categories {
        let items: Vec<&MemoryItem> = memories
            .iter()
            .filter(|m| m.category == cat && m.status == MemoryStatus::Active && !m.tombstone)
            .collect();

        if items.is_empty() {
            continue;
        }

        out.push_str(&format!("## {title}\n\n"));
        for item in items {
            out.push_str(&format!("- **[{}]**: {}\n", item.key_phrase, item.rule_text));
            if let Some(sql) = &item.sql_snippet {
                out.push_str(&format!("  - SQL: `{sql}`\n"));
            }
            if (item.importance - 0.5).abs() > 0.01 {
                out.push_str(&format!("  - Importance: {:.2}\n", item.importance));
            }
        }
        out.push('\n');
    }

    out
}

#[derive(Debug, Clone)]
pub struct ParsedRule {
    pub category: MemoryCategory,
    pub key_phrase: String,
    pub rule_text: String,
    pub sql_snippet: Option<String>,
    pub importance: f32,
}

/// Parses a Markdown document into structured rules.
pub fn parse_markdown_rules(content: &str) -> Vec<ParsedRule> {
    let mut rules = Vec::new();
    let mut current_category = MemoryCategory::Quirk;

    let lines: Vec<&str> = content.lines().collect();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i].trim();

        if line.starts_with("## ") {
            let cat_name = line[3..].trim().to_lowercase();
            if cat_name.contains("metric") {
                current_category = MemoryCategory::Metric;
            } else if cat_name.contains("join") {
                current_category = MemoryCategory::Join;
            } else if cat_name.contains("quirk") {
                current_category = MemoryCategory::Quirk;
            } else if cat_name.contains("preference") {
                current_category = MemoryCategory::Preference;
            }
            i += 1;
            continue;
        }

        if let Some(open_bracket) = line.find("**[") {
            if let Some(close_offset) = line[open_bracket + 3..].find("]**:") {
                let actual_close = open_bracket + 3 + close_offset;
                let key_phrase = line[open_bracket + 3..actual_close].trim().to_string();
                let rule_text = line[actual_close + 4..].trim().to_string();

                let mut sql_snippet: Option<String> = None;
                let mut importance = 0.5f32;

                // Look ahead for sub-bullets
                while i + 1 < lines.len() {
                    let next_line = lines[i + 1].trim();
                    if next_line.starts_with('-') || next_line.starts_with('*') {
                        if next_line.contains("**[") && next_line.contains("]**:") {
                            break;
                        }
                        let sub = next_line
                            .trim_start_matches(|c: char| c == '-' || c == '*' || c.is_whitespace())
                            .trim();
                        let sub_lower = sub.to_lowercase();
                        if sub_lower.starts_with("sql:") {
                            let sql = sub[4..].trim().trim_matches('`').to_string();
                            if !sql.is_empty() {
                                sql_snippet = Some(sql);
                            }
                        } else if sub_lower.starts_with("importance:") {
                            if let Ok(val) = sub[11..].trim().parse::<f32>() {
                                importance = val.clamp(0.0, 1.0);
                            }
                        }
                        i += 1;
                    } else if next_line.is_empty() {
                        i += 1;
                    } else {
                        break;
                    }
                }

                if !key_phrase.is_empty() && !rule_text.is_empty() {
                    rules.push(ParsedRule {
                        category: current_category.clone(),
                        key_phrase,
                        rule_text,
                        sql_snippet,
                        importance,
                    });
                }
            }
        }

        i += 1;
    }

    rules
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_markdown_export_and_import_roundtrip() {
        let md = r#"# Lucent Database Rules: postgres-prod

## Metrics
- **[active_users]**: Users with status = 'active' and last_login > 30 days
  - SQL: `status = 'active' AND last_login_at > now() - interval '30 days'`
  - Importance: 0.90

## Joins
- **[orders_to_users]**: Join orders to users via user_id
  - SQL: `orders.user_id = users.id`
"#;

        let parsed = parse_markdown_rules(md);
        assert_eq!(parsed.len(), 2);

        assert_eq!(parsed[0].category, MemoryCategory::Metric);
        assert_eq!(parsed[0].key_phrase, "active_users");
        assert_eq!(parsed[0].importance, 0.90);
        assert_eq!(
            parsed[0].sql_snippet.as_deref(),
            Some("status = 'active' AND last_login_at > now() - interval '30 days'")
        );

        assert_eq!(parsed[1].category, MemoryCategory::Join);
        assert_eq!(parsed[1].key_phrase, "orders_to_users");
    }
}
